### ISSUE TITLE
Missing DLLsForEpsonDriver.h

### ISSUE THREAD

**Issue by joeromanoBG** [gavanderhoorn/epson_experimental#13]
Wanted to try reviving this and see if I could get it running, but noticed DLL file stored has some issues with newer Windows10 systems (looks like some common reference libraries have changed). Went to go regenerate the DLL from DLLsForEpsonDriver.cpp but noticed in recreating the project that the DLLsForEpsonDriver.h file is not checked in.

**Comment by gavanderhoorn** [comment]
Seems you're correct.

I don't have that file either.

Perhaps @l-castelli, @JeroenDM or @davidDS96 would know how to get hold of a copy.

**Comment by gavanderhoorn** [comment]
Otherwise we'll have to recreate it.

Note that I don't have access to an Epson robot, so I won't be able to assist.

**Comment by joeromanoBG** [comment]
Thanks for confirming. If anyone can dig up the old project it would be useful.
I will try to recreate and submit if I get anything functional.

I also am working thru the Epson simulator (no real robot).

**Comment by JeroenDM** [comment]
Sadly, I have no remote access to the server at work where I suspect it could be, and our campus is closed down. I will ask some colleges.

I hope we can find it for you.

**Comment by JeroenDM** [comment]
Also, we still have the EPSON robot, but I personally have no experience with it. If you have further questions I can try to find someone with knowledge on the subject and time to answer them :)

**Comment by gavanderhoorn** [comment]
Thanks @JeroenDM. It would be great if we could add that one missing file.

I've searched my old emails, but can't find anything related unfortunately.

**Comment by JeroenDM** [comment]
Mmm, bad news. The file is probably on the computer still with the robot, in a different lab that is not ours and that is closed down due to COVID-19. Could you wait a couple of weeks maybe?

I have no idea how difficult it is to recreate the file, but probably the [original thesis text](https://documentserver.uhasselt.be//handle/1942/22347) will be useful. (The appendix contains some header files, but I don't think the one you're looking for is included.)

**Comment by gavanderhoorn** [comment]
We can probably recreate it.

IIRC, it's essentially just the prototypes of the functions in the `.cpp`.

Thanks for trying @JeroenDM.

**Comment by joeromanoBG** [comment]
Yes, it was fairly straightforward. 
I did have a few other minor changes to get working on Visual Studio C++ 2019 and Windows 10.


https://github.com/joeromanoBG/epson_experimental/commit/55d72a0f4ccadae97a9f3010182fb0349cbc7f62

It is perhaps worth checking in the full project. Linking the .def file from within VC++ was something I did not understand (I don't have much experience with DLL files) and took awhile to figure out to generate a properly functional DLL that Epson RC+ would accept.

**Comment by gavanderhoorn** [comment]
All the formatting changes in `DLLsForEpsonDriver.cpp` make it a bit hard to see what was changed there (apparently not a lot: [diff without whitespace changes](https://github.com/joeromanoBG/epson_experimental/commit/55d72a0f4ccadae97a9f3010182fb0349cbc7f62?w=1)).

It would be great @joeromanoBG if you could submit the `.h` you created in a PR.

We'll keep it open till we can compare it with the one which hopefully is still available on the PC which @JeroenDM mentioned, but it would be good to have it in a PR already.

**Comment by gavanderhoorn** [comment]
Note btw: performance of this driver is not very good yet. This is/was known, but as there was limited time in the msc work of both original authors, they focused on functionality first.

**Comment by JeroenDM** [comment]
@davidDS96 retrieved the files from the lab.

The header files turns out to be :drum: :drum: :drum: 
```C++
// The following ifdef block is the standard way of creating macros which make exporting 
// from a DLL simpler. All files within this DLL are compiled with the DLLSFOREPSONDRIVER_EXPORTS
// symbol defined on the command line. this symbol should not be defined on any project
// that uses this DLL. This way any other project whose source files include this file see 
// DLLSFOREPSONDRIVER_API functions as being imported from a DLL, whereas this DLL sees symbols
// defined with this macro as being exported.
#ifdef DLLSFOREPSONDRIVER_EXPORTS
#define DLLSFOREPSONDRIVER_API __declspec(dllexport)
#else
#define DLLSFOREPSONDRIVER_API __declspec(dllimport)
#endif

// This class is exported from the DLLsForEpsonDriver.dll
class DLLSFOREPSONDRIVER_API CDLLsForEpsonDriver {
public:
	CDLLsForEpsonDriver(void);
	// TODO: add your methods here.
};

extern DLLSFOREPSONDRIVER_API int nDLLsForEpsonDriver;

DLLSFOREPSONDRIVER_API int fnDLLsForEpsonDriver(void);
```
There were also some other files that could be useful. All of the artifacts are available in this zip folder
[DLLsForEpsonDriver.zip](https://github.com/gavanderhoorn/epson_experimental/files/4481743/DLLsForEpsonDriver.zip)

Because I had some issues with opening the files in the zip I created,  I also did a pull request (#14) with most of them.

**Comment by joeromanoBG** [comment]
Thanks for digging it up!
I think it is useful to keep that zip attached since there are some VC++ project subtleties to get a good working DLL out (still not sure if the one on github here is broken-for-all or just broken-for-me).

I was able to create a working one on my own and verified this does do reasonable things in the RC+ simulator. Currently seeing if can get it working a bit smoother and will report any significant improvements over the existing project.

**Comment by gavanderhoorn** [comment]
Let's keep this open until #14 gets merged.

**Comment by gavanderhoorn** [comment]
Closing as #14 added the missing files.
